server:
  port: 9000
spring:
  kafka:
    listener:
      concurrency: 3
      type: batch
    consumer:
      bootstrap-servers: localhost:9092
      group-id: group_id
      auto-offset-reset: earliest
      max-poll-records: 90
      fetch-max-wait: 200ms
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      heartbeat-interval: 11s
      properties:
        session.timeout.ms: 20000
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
my.kafka:
  topic: users
  group: my_group
management:
  endpoint:
    health:
      enabled: true
      show-details: always
